
export const DEPARTMENTS = [
  "Computer Science and Engineering (CSE)",
  "Electrical and Electronic Engineering (EEE)",
  "Civil and Environmental Engineering (CEE)",
  "Chemical Engineering and Polymer Science (CEP)",
  "Industrial and Production Engineering (IPE)",
  "Petroleum and Geomineral Resources Engineering (PME)",
  "Architecture (ARC)",
  "Physics",
  "Chemistry",
  "Mathematics",
  "Statistics",
  "Geography and Environment",
  "Public Administration",
  "Economics",
  "Social Work",
  "Political Studies",
  "Sociology",
  "Anthropology",
  "Business Administration",
  "English",
  "Bangla",
  "Biochemistry and Molecular Biology",
  "Genetic Engineering and Biotechnology",
  "Forestry and Environmental Science",
  "Food Engineering and Tea Technology",
] as const;

export const FIELDS_OF_STUDY = [
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Cybersecurity",
  "Software Engineering",
  "Cloud Computing",
  "Internet of Things (IoT)",
  "Bioinformatics",
  "Renewable Energy",
  "Structural Engineering",
  "Environmental Science",
  "Organic Chemistry",
  "Applied Mathematics",
  "Quantum Physics",
  "Macroeconomics",
  "Sustainable Development",
  "Public Policy",
  "Linguistics",
  "Digital Marketing",
  "Genetics",
  "Agriculture",
] as const;

export type Department = typeof DEPARTMENTS[number];
export type FieldOfStudy = typeof FIELDS_OF_STUDY[number];
